version: "2"
services:
    www:
        build: .
        environment:
           UPLOAD_LIMIT: 100M
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html/
            - ./.htaccess:/var/www/html/.htaccess
            - ./app/config/custom.php.ini:/usr/local/etc/php/custom.d
        links:
            - db
        networks:
            - default
    db:
        image: mysql
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: 2022_git
            MYSQL_USER: root
            MYSQL_PASSWORD: IySY?Pk7!!mH
            MYSQL_ROOT_PASSWORD: IySY?Pk7!!mH
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin
        ports :
            - "8081:80"
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: IySY?Pk7!!mH
            MYSQL_ROOT_PASSWORD: IySY?Pk7!!mH
        links:
            - db:db
        volumes:
            - ./app/config/php.ini:/usr/local/etc/php/php.ini